### PR TITLE
Making types in Microsoft.Extensions.DependencyInjection public

### LINKED ISSUE #315: Consider making types in Microsoft.Extensions.DependencyInjection public
For instance:
https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Extensions.DependencyInjection/ServiceProvider.cs#L18

We could place them in an `Internal` namespace if necessary..

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes #315

### CODE REVIEW

**Comment by Eilon** [comment]
And what's the real reason for this? What does this help?

**Comment by pranavkm** [comment]
Nothing in particular?

**Comment by Eilon** [comment]
Then let's not do it now? :smile: These are some pretty obscure types...

**Comment by pranavkm** [comment]
:crying_cat_face:

**Comment by Eilon** [comment]
I know, I know, so sad :sob:

**Comment by DovydasNavickas** [comment]
Hmmm... I found this while looking at a way to use DI for testing.
Of course, there is `TestServer` with the whole `Startup.cs` and its `ConfigureServices` and `Configure` mechanism, but my application does polling from service bus and not HTTP requests handling, which makes it quite hard to use the TestServer.
Http messages only control the polling and processing mechanisms and report current status, if requested.
I suppose there is no way to get the same DI implementation that I get in web application, is there?
Maybe I'm doing something fundamentally wrong?

**Comment by pranavkm** [comment]
@DovydasNavickas could you file a new issue stating what you're trying to do and why you can't get it to work?

**Comment by DovydasNavickas** [comment]
Done: https://github.com/aspnet/DependencyInjection/issues/445

**Pull request closed without merging**
