### PR TITLE
Rename AddInstance to AddSingleton

### LINKED ISSUE #319: Rename AddInstance to AddSingleton
The name `AddInstance` doesn't make it super clear what the lifetime is of the object. (If you stop and think about it, it can only be Singleton, but every time I call that method I have to stop and think about it.)

So, we should rename `AddInstance` to `AddSingleton`, or perhaps `AddSingletonInstance`.

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes #319

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @Eilon \ @davidfowl

**Comment by davidfowl** [comment]
@pranavkm Everything will start to fail because we have warnings as errors. Make sure you do a pass through the other repos.

:shipit:

**Comment by pranavkm** [comment]
@Eilon had some concerns about using `ObsoleteAttribute`.

**Comment by Eilon** [comment]
Yeah I'm not sure why we'd go out of the way to mark APIs as obsolete. There are much larger changes than this that have gone through. That's why we have the Announcements repo.

**Comment by pranavkm** [comment]
Ok. I'll get rid of `AddInstance`

**Pull request closed without merging**
