### PR TITLE
[Fixes #397] Add specification tests that verifies it is safe to cach…

### LINKED ISSUE #397: Add specification tests that verifies it is safe to cache \ reuse IServiceScopeFactory

### PR DESCRIPTION
**Pull request by kichalla**
…e\reuse IServiceScopeFactory

@davidfowl @pranavkm

### CODE REVIEW

**Comment by kichalla** [comment]
ping

**Comment by kichalla** [comment]
cc @khellang

**Comment by khellang** [comment]
LGTM :shipit: Is there a particular reason you're testing this?

**Comment by davidfowl** [comment]
@khellang  https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/RequestServicesContainerMiddleware.cs

**Comment by pranavkm** [comment]
:shipit:

**Pull request merged**
