### PR TITLE
Build with xml-docs-test only if src folder exists.

### PR DESCRIPTION
**Pull request by cesarblum**
cc @victorhurdugaci

### CODE REVIEW

**Comment by victorhurdugaci** [comment]
I don't think this target is needed anymore. Maybe a quick workaround is to remove the body of the sake target

**Comment by victorhurdugaci** [comment]
cc @pranavkm

**Comment by victorhurdugaci** [comment]
This is not needed anymore

**Comment by pranavkm** [comment]
Yup. The new CLI takes care of this.

**Pull request closed without merging**
