### PR TITLE
Unity added support for Microsoft.Extensions.DependencyInjection

### PR DESCRIPTION
**Pull request by ENikS**
Please add Unity to the list of compatible containers

### CODE REVIEW

**Comment by davidfowl** [comment]
Last I checked there were some incompatibilities making unity work. Looking at the linked project it seems like it passes all of the specification tests?

**Comment by ENikS** [comment]
Yes, these were fixed. It now passes [all tests](https://ci.appveyor.com/project/IoC-Unity/microsoft-dependency-injection/build/2.0.5.62)

**Comment by davidfowl** [comment]
@ENikS 👏  LGTM

**Comment by ENikS** [comment]
Thank you

**Pull request merged**
