### PR TITLE
Make TService type param more permissive on Add*<TService, TImplementation>()

### PR DESCRIPTION
**Pull request by Mardoxx**
Fixes aspnet/Home#2828

### CODE REVIEW

**Comment by Mardoxx** [comment]
Will add tests after feedback (if this is a genuine issue)

**Comment by davidfowl** [comment]
Is this a breaking change?

**Comment by Mardoxx** [comment]
Not entirely sure. Superficially I don't think so!

**Comment by Mardoxx** [comment]
Okay, it's been picked up as a breaking change - but is it really?

This is a strange one as it clearly works when [not passing template params](https://github.com/aspnet/DependencyInjection/blob/5238b8ccf7bc6592a5c6a1da8635ed2871cfabbf/src/DI.Specification.Tests/DependencyInjectionSpecificationTests.cs#L412).

What's different between

this
```cs
    public static IServiceCollection RegisterScopedTestService<TService, TImplementation>(this IServiceCollection services)
        where TImplementation : class, TService
    {
        return services.AddScoped<TService, TImplementation>();
    }
```

and
    public void SomeFunction(IServiceCollection services)
    {
        services.AddScoped<ITestService, TestService>();
    }

given
```cs
    public interface ITestService
    {
    }

    public class TestService : ITestService
    {
    }
```

The signature still expects TService to be a reference type, but the latter is working. What am I missing here?

**Comment by davidfowl** [comment]
You just need to add `where TService : class` so that you match the constraints of the method you're calling.

**Comment by Mardoxx** [comment]
Just realised that! 😄 

Now I'm wondering if the constraint is actually required. Under what circumstances could you register something which fails either?

```
TImplementation : class
TImplementation : TService, class
```

but passes with

```
TImplementation : class
TImplementation : TService, class
```

**Comment by davidfowl** [comment]
> Now I'm wondering if the constraint is actually required. Under what circumstances could you register something which fails these constraints

It may not be possible but I'm not sure it matters because we wouldn't make a breaking change like this regardless.

**Comment by Mardoxx** [comment]
interesting. I'll post on SO, see if anyone can out of curiosity.

Very understandable! Thanks 😄

**Comment by Mardoxx** [comment]
So after a little reading it would seem that the current definition is more technically correct, even if it's not necessary. I suspect the choice was taken to have both constraints there as it clearly shows that TService must be a reference type!

**Comment by Mardoxx** [comment]
https://stackoverflow.com/a/48471755/3515174 Brilliant insight here 😄

**Pull request closed without merging**
