### PR TITLE
Add generic TryAdd with implementation factory

### PR DESCRIPTION
**Pull request by henkmollema**
Adds a generic `TryAdd` (transient/scoped/singleton) with a generic implementation factory as parameter.

### CODE REVIEW

**Comment by henkmollema** [comment]
Is there any interest in such extension method? If so, I will add some tests.

**Comment by pranavkm** [comment]
cc @Eilon 

@henkmollema shouldn't need tests since they're simply calling into `IServiceCollection.TryAdd`.

**Comment by Eilon** [comment]
I'm not super familiar with this set of APIs, so if it looks good and useful to you guys, that's fine with me.

**Comment by pranavkm** [comment]
We don't use this overload in our code, but I can see it being useful for other users. I'll merge it in. I guess the bot decided this isn't CLA worthy.

**Comment by pranavkm** [comment]
Oh never mind, didn't see the bot add the tag.

**Comment by pranavkm** [comment]
Merged in https://github.com/aspnet/DependencyInjection/commit/4b86215bc8d1b47a0901c3585637633d4e115b6e

**Comment by henkmollema** [comment]
I need it in one of my projects, figured someone else might too.

What about the CLA? It says signed.

**Comment by henkmollema** [comment]
Oh it's done. Thanks! :+1:

**Pull request closed without merging**
