### PR TITLE
Make DependencyInjection package use NET46 compatible Ref …

### PR DESCRIPTION
**Pull request by mjsabby**
…Assemblies.

This has no functionality impact but allows the assembly to be compatible with more frameworks.

### CODE REVIEW

**Comment by mjsabby** [comment]
cc @NTaylorMullen

**Comment by davidfowl** [comment]
Why didn't we merge 
 this ?

**Comment by mjsabby** [comment]
I see it merged.

**Comment by NTaylorMullen** [comment]
It's merged :smile:. I just left a comment on the other PR @mjsabby did saying it was merged because it didn't auto close it and mark as merged.

**Comment by davidfowl** [comment]
I'm asking a different question.... As in it should not be merged.

**Comment by pranavkm** [comment]
This is currently breaking Coherence. Why did we merge it in again?

**Comment by NTaylorMullen** [comment]
It's out

**Pull request merged**
