### PR TITLE
Make ServiceProvider class public

### PR DESCRIPTION
**Pull request by couven92**
Ref. Issue #476

### CODE REVIEW

**Comment by davidfowl** [comment]
I feel like we should rename this class if we make it public. `ServiceProvider` just seems too.. I dunno generic.

/cc @Eilon @pakrym @halter73

**Comment by couven92** [comment]
Some of the collections often inherit from *CollectionName* **Base**

So maybe: `ServiceProviderBase`?

**Comment by davidfowl** [comment]
It's not a base class, it's a default implementation of `IServiceProvider`

**Comment by couven92** [comment]
`ServiceRealizer`? `DIServiceProvider`? `DefaultServiceProvider` (ref `DefaultServiceProviderFactory``)?

I suck at naming, so I do not really have much better suggestions...

**Comment by cwe1ss** [comment]
Would be a lot cooler if you had product names for these libraries! Now you have to use `MicrosoftExtensionsDependencyInjectionServiceProvider`!  😀

**Comment by pakrym** [comment]
I think `DefaultServiceProvider` should be fine

**Comment by halter73** [comment]
I question the wisdom of making ServiceProvider public in the first place. It doesn't serve much of a purpose.

It's not as if using it as a base class achieves anything considering it's only ever exposed as an IServiceProvider and IDisposable. Not coincidentally, GetService and Dispose are the only public members on the class. There are no protected members. This means anything you could achieve with inheritance, you could achieve about just as easily with encapsulation.

Making GetService virtual isn't nearly as useful as it might seem at first glance. The GetService method isn't used for transitive/nested/recursive/what-ever-you-call-them services. That of course makes the default fallback to a root level provider as suggested in #476 difficult to implement in any useful way. At least not in any way that couldn't be achieved just as well with encapsulation. And that's not even getting into the issues related to scoping.

If we do decide to make ServiceProvider public, I would like to see the actual code that needs to reference it.

**Comment by davidfowl** [comment]
@halter73 agreed. See https://github.com/aspnet/DependencyInjection/issues/476#issuecomment-275557577

**Comment by Eilon** [comment]
Let's do another DI triage this coming week. I'll set it up.

**Comment by couven92** [comment]
I have renamed the `ServiceProvider` to `DefaultServiceProvider` as @pakrym suggested in https://github.com/aspnet/DependencyInjection/pull/477#issuecomment-275570866

**Comment by davidfowl** [comment]
Closing this out until we get more clarity on if this is needed

**Pull request closed without merging**
