### PR TITLE
Revert "Removing Autofac tests"

### PR DESCRIPTION
**Pull request by pranavkm**
This reverts commit a514aabded31e93a9b9a000f7677dafce245d873.

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @Eilon

**Comment by Eilon** [comment]
:shipit:

**Comment by khellang** [comment]
Just curious; Why are you keeping these tests around? Would you be interested in the same for StructureMap?

**Comment by pranavkm** [comment]
@khellang the plan is to remove this once https://github.com/aspnet/DependencyInjection/issues/270 is completed.

**Comment by khellang** [comment]
Ah, awesome! Thanks :smile: Right now we're using this repo as a submodule to run the tests: https://github.com/structuremap/structuremap.dnx/tree/master/lib

**Pull request closed without merging**
