### PR TITLE
Added benchmarks project and basic benchmark 

### PR DESCRIPTION
**Pull request by davidfowl**
- Added a benchmark project (using benchmark.NET)
- Copied most of the infrastructure from kestrel and tweaked it a little 
- Added a resolve benchmark

|    Method |        Mean |    StdErr |     StdDev | Scaled | Scaled-StdDev |            RPS |  Gen 0 | Allocated |
|---------- |------------ |---------- |----------- |------- |-------------- |--------------- |------- |---------- |
|      NoDI |   6.9489 ns | 0.1808 ns |  0.9905 ns |   1.00 |          0.00 | 143,906,789.32 | 0.0112 |      24 B |
| Transient |  51.2131 ns | 0.3905 ns |  2.1389 ns |   7.47 |          0.82 |  19,526,255.52 | 0.0091 |      24 B |
|    Scoped | 106.3770 ns | 4.2441 ns | 23.2460 ns |  15.53 |          3.71 |   9,400,532.68 |      - |       0 B |
| Singleton | 123.1784 ns | 3.6458 ns | 19.9689 ns |  17.98 |          3.42 |   8,118,307.04 |      - |       0 B |

### CODE REVIEW

**Comment by khellang** [comment]
Does RPS bring any value here?

**Comment by davidfowl** [comment]
@khellang That's a good question. I like those big numbers 😄

**Comment by benaadams** [comment]
> Does RPS bring any value here?

Its easier to evaluate than `0.0001 ns`

**Comment by benaadams** [comment]
Quite fast... might need to stick it in a loop to be accurate :)

**Comment by pakrym** [comment]
I don't like copying same code around, would prefer having package with benchmark.net specific code

**Comment by davidfowl** [comment]
> I don't like copying same code around, would prefer having package with benchmark.net specific code

I knew you were going to say that. Will postpone this until then.

**Comment by pakrym** [comment]
`Program.cs` code can be shared too

**Comment by davidfowl** [comment]
Like 5% of the code, the enum (which is a hack) isn't sharable. It really needs to be based on type names, not an enum.

**Comment by pakrym** [comment]
We need to make it type based not enum based anyway, so it would be 100%

**Comment by davidfowl** [comment]
It needs to be rewritten is my point. Anyways, I'll add a package to Common with those 2 shared functions.

**Comment by davidfowl** [comment]
Also filed https://github.com/dotnet/BenchmarkDotNet/issues/386

**Comment by arespr** [comment]
here is nice comparison:

http://www.palmmedia.de/blog/2011/8/30/ioc-container-benchmark-performance-comparison

**Comment by davidfowl** [comment]
@arespr yes, see https://github.com/aspnet/DependencyInjection/issues/490

**Comment by pakrym** [comment]
@davidfowl do we want to contribute RPS column to BDN?

**Comment by davidfowl** [comment]
@pakrym Yes, I was just asking @benaadams if he wrote it. It really belongs there.

**Comment by benaadams** [comment]
RPS came from @mattwarren

**Pull request merged**
