### PR TITLE
Switching to using dotnet generations TFM

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @davidfowl

**Comment by khellang** [comment]
What is `dotnet5.4`? :confused:

**Comment by Eilon** [comment]
:shipit:

**Comment by Eilon** [comment]
@khellang it's something new and amazing :smile: Stay tuned to the https://github.com/aspnet/Announcements/issues/ repo regarding this.

**Pull request closed without merging**
