### PR TITLE
Remove portable target

### PR DESCRIPTION
**Pull request by bricelam**
Given the removal of ANIs, this isn't needed anymore

### CODE REVIEW

**Comment by pranavkm** [comment]
:shipit:

**Comment by yishaigalatzer** [comment]
@bricelam is this merged?

**Comment by davidfowl** [comment]
Why do this?

**Comment by bricelam** [comment]
@yishaigalatzer Not merged yet, we still depend on it.
@davidfowl After aspnet/EntityFramework#1682 is merged, they won't be needed anymore. We may bring them back if we decide to target Windows Store/Phone 8.1, but I'm hoping for just Windows 10.

**Comment by davidfowl** [comment]
@bricelam kewl. Can we nuke it now then?

**Pull request closed without merging**
