### PR TITLE
Updating to RTM builds of xunit

### PR DESCRIPTION
**Pull request by pranavkm**
cc @dougbu \ @khellang

### CODE REVIEW

**Comment by dougbu** [comment]
Just curious: Are we going to be able to remove _every_ direct `System.Diagnostics.Process` dependency? :smiley_cat:

**Comment by dougbu** [comment]
:shipit:

**Comment by pranavkm** [comment]
Well, at least the ones @davidfowl added for tests.

**Comment by khellang** [comment]
Not sure why I was cc'd but LGTM :shipit: :stuck_out_tongue:

**Pull request merged**
